version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: "npm install"
      - run: "npm build"
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: "npm install"
      - run: "npm test"
  analyze:
    docker:
        - image: circleci/node:latest
    steps:
      - checkout
      - run: "npm install"
      - run: "npm build"
      - run: "analyze-bundle"

workflows:
  version: 2
  first_workflow:
    jobs:
      - build
      - test
      - analyze
